# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-09 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20180609_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': '菜单表'},
        ),
        migrations.RenameField(
            model_name='role',
            old_name='url_name',
            new_name='menu',
        ),
    ]
